// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var appContainer = Css.style(/* :: */[
      Css.display(/* flex */-1010954439),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.justifyContent(/* spaceEvenly */-1016061555),
          /* :: */[
            Css.maxWidth(/* `px */[
                  25096,
                  700
                ]),
            /* :: */[
              Css.margin(/* auto */-1065951377),
              /* :: */[
                Css.boxSizing(/* borderBox */9307263),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var heading = Css.style(/* :: */[
      Css.display(/* block */888960333),
      /* :: */[
        Css.color(Css.grey),
        /* [] */0
      ]
    ]);

exports.appContainer = appContainer;
exports.heading = heading;
/* appContainer Not a pure module */
