// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function getIcon(icon) {
  if (icon) {
    return React.createElement("svg", {
                height: "18",
                width: "18",
                viewBox: "0 0 24 24",
                xmlns: "http://www.w3.org/2000/svg"
              }, React.createElement("path", {
                    d: "M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"
                  }), React.createElement("path", {
                    d: "M0 0h24v24H0z",
                    fill: "none"
                  }));
  } else {
    return React.createElement("svg", {
                height: "18",
                width: "18",
                viewBox: "0 0 24 24",
                xmlns: "http://www.w3.org/2000/svg"
              }, React.createElement("path", {
                    d: "M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"
                  }), React.createElement("path", {
                    d: "M0 0h24v24H0z",
                    fill: "none"
                  }));
  }
}

exports.getIcon = getIcon;
/* react Not a pure module */
